---
- hosts: apache
  sudo: yes
  tasks:
  - name: remove the Apache package
    yum:
      name: httpd
      state: absent

  - name: close port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: disabled

  - name: Remove file (delete file)
      file:
        path: /var/www/html/index.html
        state: absent
